export const path = {
  home: "/",
  menu: "/menu",
  table: "/table/:tableNumber",
  myOrder: "/my-order",
  login: "/login",
  manage: "/manage",
  kitchen: "/manage/kitchen",
  manageOrder: "/manage/orders",
  manageTable: "/manage/tables",
  manageUser: "/manage/users",
  manageFood: "/manage/foods",
  manageCategory: "/manage/categories",
  manageSettings: "/manage/settings",
} as const;
